### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by batCoder95** [trailbehind/DeepOSM#49]
Hey Guys, I am B.Tech. CS graduate and I have been working on image processing since 1.5 years. I would like to contribute to this project. Can anyone assign me some task, doesn't matter how simple or tough ?

**Comment by andrewljohnson** [comment]
@batCoder9395 do you think you can extend the analysis to buildings?

This would require 1) extracting the buildings polygons from OSM data, 2) shading in the inside of the polygons when creating the bitmap representation of the building data, 3) adding a parameter to bin/create_training_data.py. Some polygons have holes too, so there is a little thinking required to shade the bitmap.

I think the whole pipeline would otherwise work, and then the command line tool could do buildings too, and we could start experimenting with those. 

There is more info in issue #25 too

**Comment by batCoder95** [comment]
Hey Andrew,
I read that DeepOSM can run on Mac and Linux. I am a windows user. Is there any way around this ?

**Comment by andrewljohnson** [comment]
Never tried, but Docker should be good on Windows. If it works on Windows, please do a PR on the README.

**Comment by andrewljohnson** [comment]
closing this now, let me know if you have questions on buildings!
